name: Validate cnames_active.js

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: js-org/js.org-cleanup
          path: cleanup

      - uses: actions/setup-node@v2
        with:
          node-version-file: cleanup/.nvmrc
          cache: npm
          cache-dependency-path: cleanup/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: cleanup

      - name: Validate cnames_active.js
        run: node index.js --validate ../cnames_active.js
        working-directory: cleanup
